language: node_js
node_js:
- '6.9'
install:
- npm install
before_install:
- openssl aes-256-cbc -K $encrypted_ea7c23c92036_key -iv $encrypted_ea7c23c92036_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 138.197.225.210\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
# 添加一个名为after_success的钩子，并写入你需要执行部署操作的命令
after_success:
- ssh root@138.197.225.210 '/data/shell/deploy-zh-zhaobing-site.sh'
